# PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0ac7054352386c186
---
#pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-pvc
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static #name must be given  pv mrtadataname
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  
---
#POD
apiVersion: v1
kind: Pod
metadata:
 name: nginx
 labels:
   purpose: ebs-static-demo
   project: roboshop
spec:
  nodeSelector:
  topology.kubernetes.io/zone: us-east-1d
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /user/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-static-pvc #clime name is pvc name
---
#SVC
apiVersion: v1
kind: Service
metadata:
  name: ebs-static-service
  labels:
    purpose: ebs-static-demo
    project: roboshop
spec:
  type: LoadBalancer
  selector:
   purpose: ebs-static-demo
   Project: roboshop
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port

#create volumes in kuberentes
#Attach to EBSpolicy one node
#install drivers
#create pv pvc and pod service load balancer
#check in browser
#once done delete all volumes

